[project]
name = "trapper-zooniverse"
version = "0.1.0"
description = "A bridge for integrating Trapper with Zooniverse projects"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "typer-config >=1.4.2",
    "typer>=0.20.0",
    "rich>=14.2.0",
    "trapper-client",
    "panoptes-client >= 1.7.1",
    "python-dotenv >= 1.1.1",
    "pyyaml >=6.0.3",
    "pyjson >=1.4.1",
    "pydantic>=2.12.0",
    "dynaconf>=3.2.12",


]

[dependency-groups]
dev = [
    "babel>=2.17.0",
    "pillow>=12.0.0",
    "pyright>=1.1.407",
    "pytest>=8.4.2",
    "ruff>=0.14.3",
    "sphinx>=8.2.3",
    "sphinx-autodoc-typehints>=3.5.2",
    "sphinx-rtd-theme>=3.0.2",
]


[project.scripts]
trapper-zooniverse = "trapper_zooniverse.ui.typer.main:app"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.uv]
package = true

[tool.ruff]
# Set the maximum line length to 79.
line-length = 120

[tool.ruff.lint]
# Add the `line-too-long` rule to the enforced rule set.
extend-select = ["E501"]

[tool.uv.sources]
trapper-client = { git = "https://github.com/ijfvianauhu/trapper-client.git", rev = "main" }

