[LOGGER]
loglevel = 1
filename = ""

[TRAPPER]

trapper_username= "trapper_client@uhu.es"
trapper_password= "pass"
trapper_url= "https://wildintel-trap.uhu.es/"
trapper_token= ""

[ZOONIVERSE]
zooniverse_username= ""
zooniverse_password= ""
zooniverse_project_id= ""

[ZOONIVERSE_CONNECTOR]
upload_collection_n_images_seq=5
upload_collection_max_interval=120
upload_collection_attempts=5
upload_collection_delay=15
upload_collection_max_attempts_per_subject=5
upload_collection_delay_seconds_per_subject=30